In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib
plt.style.use('ggplot')
from matplotlib.pyplot import figure

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

pd.options.mode.chained_assignment = None
# Provide the file path
file_path = r'C:\Users\nzen4\Downloads\AdventureWorks Sales.xlsx'

# Read the Excel file into a DataFrame
df1 = pd.read_excel(file_path)

# Create an ExcelFile object
xls = pd.ExcelFile(file_path)

# Get the sheet names
sheet_names = xls.sheet_names

# Print the sheet names
for sheet_name in sheet_names:
    print(sheet_name)

# Now you can use the DataFrame 'df1' for further analysis or processing

Sales Order_data
Sales Territory_data
Sales_data
Reseller_data
Date_data
Product_data
Customer_data

In [2]:
#define all sheet
df_sales_order_data = pd.read_excel(xls,'Sales Order_data')
df_sales_territory_data = pd.read_excel(xls,'Sales Territory_data')  
df_sales_data = pd.read_excel(xls, 'Sales_data')
df_reseller_data = pd.read_excel(xls, 'Reseller_data')
df_date_data = pd.read_excel(xls, 'Date_data')
df_product_data = pd.read_excel(xls, 'Product_data')
df_customer_data = pd.read_excel(xls, 'Customer_data')

View Sheet 'Sales_data'

In [3]:
print(df_sales_order_data)
print(df_sales_territory_data)
print(df_sales_data)
print(df_reseller_data)
print(df_date_data)
print(df_product_data)
print(df_customer_data)

         Channel  SalesOrderLineKey Sales Order Sales Order Line
0       Reseller           43659001     SO43659      SO43659 - 1
1       Reseller           43659002     SO43659      SO43659 - 2
2       Reseller           43659003     SO43659      SO43659 - 3
3       Reseller           43659004     SO43659      SO43659 - 4
4       Reseller           43659005     SO43659      SO43659 - 5
...          ...                ...         ...              ...
121248  Internet           75122001     SO75122      SO75122 - 1
121249  Internet           75122002     SO75122      SO75122 - 2
121250  Internet           75123001     SO75123      SO75123 - 1
121251  Internet           75123002     SO75123      SO75123 - 2
121252  Internet           75123003     SO75123      SO75123 - 3

[121253 rows x 4 columns]
    SalesTerritoryKey          Region         Country          Group
0                   1       Northwest   United States  North America
1                   2       Northeast   United States  North America
2                   3         Central   United States  North America
3                   4       Southwest   United States  North America
4                   5       Southeast   United States  North America
5                   6          Canada          Canada  North America
6                   7          France          France         Europe
7                   8         Germany         Germany         Europe
8                   9       Australia       Australia        Pacific
9                  10  United Kingdom  United Kingdom         Europe
10                 11    Corporate HQ    Corporate HQ   Corporate HQ
        SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  \
0                43659001          676           -1         349      20170702
1                43659002          676           -1         350      20170702
2                43659003          676           -1         351      20170702
3                43659004          676           -1         344      20170702
4                43659005          676           -1         345      20170702
...                   ...          ...          ...         ...           ...
121248           75122001           -1        15868         485      20200615
121249           75122002           -1        15868         225      20200615
121250           75123001           -1        18759         485      20200615
121251           75123002           -1        18759         486      20200615
121252           75123003           -1        18759         225      20200615

        DueDateKey  ShipDateKey  SalesTerritoryKey  Order Quantity  \
0         20170712   20170709.0                  5               1
1         20170712   20170709.0                  5               3
2         20170712   20170709.0                  5               1
3         20170712   20170709.0                  5               1
4         20170712   20170709.0                  5               1
...            ...          ...                ...             ...
121248    20200625          NaN                  6               1
121249    20200625          NaN                  6               1
121250    20200625          NaN                  6               1
121251    20200625          NaN                  6               1
121252    20200625          NaN                  6               1

        Unit Price  Extended Amount  Unit Price Discount Pct  \
0         2024.994         2024.994                        0
1         2024.994         6074.982                        0
2         2024.994         2024.994                        0
3         2039.994         2039.994                        0
4         2039.994         2039.994                        0
...            ...              ...                      ...
121248      21.980           21.980                        0
121249       8.990            8.990                        0
121250      21.980           21.980                        0
121251     159.000          159.000                        0
121252       8.990            8.990                        0

        Product Standard Cost  Total Product Cost  Sales Amount
0                   1898.0944           1898.0944      2024.994
1                   1898.0944           5694.2832      6074.982
2                   1898.0944           1898.0944      2024.994
3                   1912.1544           1912.1544      2039.994
4                   1912.1544           1912.1544      2039.994
...                       ...                 ...           ...
121248                 8.2205              8.2205        21.980
121249                 6.9223              6.9223         8.990
121250                 8.2205              8.2205        21.980
121251                59.4660             59.4660       159.000
121252                 6.9223              6.9223         8.990

[121253 rows x 15 columns]
     ResellerKey       Reseller ID         Business Type  \
0             -1  [Not Applicable]      [Not Applicable]
1              1        AW00000001  Value Added Reseller
2              2        AW00000002   Specialty Bike Shop
3              3        AW00000003             Warehouse
4              4        AW00000004  Value Added Reseller
..           ...               ...                   ...
715          697        AW00000697  Value Added Reseller
716          698        AW00000698   Specialty Bike Shop
717          699        AW00000699             Warehouse
718          700        AW00000700  Value Added Reseller
719          701        AW00000701             Warehouse

                          Reseller              City    State-Province  \
0                 [Not Applicable]  [Not Applicable]  [Not Applicable]
1                     A Bike Store           Seattle        Washington
2               Progressive Sports            Renton        Washington
3         Advanced Bike Components            Irving             Texas
4            Modular Cycle Systems            Austin             Texas
..                             ...               ...               ...
715               Brakes and Gears            Tooele              Utah
716          Western Bike Supplies        Cedar City              Utah
717     Sensational Discount Store        Kannapolis    North Carolina
718  Underglaze and Finish Company         Charlotte    North Carolina
719                   Future Bikes           Calgary           Alberta

       Country-Region       Postal Code
0    [Not Applicable]  [Not Applicable]
1       United States             98104
2       United States             98055
3       United States             75061
4       United States             78701
..                ...               ...
715     United States             84074
716     United States             84720
717     United States             28081
718     United States             28202
719            Canada           T2P 2G8

[720 rows x 8 columns]
       DateKey       Date Fiscal Year Fiscal Quarter     Month     Full Date  \
0     20170701 2017-07-01      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 01
1     20170702 2017-07-02      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 02
2     20170703 2017-07-03      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 03
3     20170704 2017-07-04      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 04
4     20170705 2017-07-05      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 05
...        ...        ...         ...            ...       ...           ...
1456  20210626 2021-06-26      FY2021      FY2021 Q4  2021 Jun  2021 Jun, 26
1457  20210627 2021-06-27      FY2021      FY2021 Q4  2021 Jun  2021 Jun, 27
1458  20210628 2021-06-28      FY2021      FY2021 Q4  2021 Jun  2021 Jun, 28
1459  20210629 2021-06-29      FY2021      FY2021 Q4  2021 Jun  2021 Jun, 29
1460  20210630 2021-06-30      FY2021      FY2021 Q4  2021 Jun  2021 Jun, 30

      MonthKey
0       201707
1       201707
2       201707
3       201707
4       201707
...        ...
1456    202106
1457    202106
1458    202106
1459    202106
1460    202106

[1461 rows x 7 columns]
     ProductKey         SKU                    Product  Standard Cost  Color  \
0           210  FR-R92B-58  HL Road Frame - Black, 58       868.6342  Black
1           211  FR-R92R-58    HL Road Frame - Red, 58       868.6342    Red
2           212   HL-U509-R      Sport-100 Helmet, Red        12.0278    Red
3           213   HL-U509-R      Sport-100 Helmet, Red        13.8782    Red
4           214   HL-U509-R      Sport-100 Helmet, Red        13.0863    Red
..          ...         ...                        ...            ...    ...
392         602     BB-8107          ML Bottom Bracket        44.9506    NaN
393         603     BB-9108          HL Bottom Bracket        53.9416    NaN
394         604  BK-R19B-44         Road-750 Black, 44       343.6496  Black
395         605  BK-R19B-48         Road-750 Black, 48       343.6496  Black
396         606  BK-R19B-52         Road-750 Black, 52       343.6496  Black

     List Price              Model      Subcategory     Category
0     1431.5000      HL Road Frame      Road Frames   Components
1     1431.5000      HL Road Frame      Road Frames   Components
2       33.6442          Sport-100          Helmets  Accessories
3       33.6442          Sport-100          Helmets  Accessories
4       34.9900          Sport-100          Helmets  Accessories
..          ...                ...              ...          ...
392    101.2400  ML Bottom Bracket  Bottom Brackets   Components
393    121.4900  HL Bottom Bracket  Bottom Brackets   Components
394    539.9900           Road-750       Road Bikes        Bikes
395    539.9900           Road-750       Road Bikes        Bikes
396    539.9900           Road-750       Road Bikes        Bikes

[397 rows x 9 columns]
       CustomerKey       Customer ID          Customer              City  \
0             -1.0  [Not Applicable]  [Not Applicable]  [Not Applicable]
1          11000.0        AW00011000          Jon Yang       Rockhampton
2          11001.0        AW00011001      Eugene Huang           Seaford
3          11002.0        AW00011002      Ruben Torres            Hobart
4          11003.0        AW00011003       Christy Zhu        North Ryde
...            ...               ...               ...               ...
18497      29479.0        AW00029479        Tommy Tang        Versailles
18498      29480.0        AW00029480         Nina Raji            London
18499      29481.0        AW00029481         Ivan Suri               Hof
18500      29482.0        AW00029482     Clayton Zhang        Saint Ouen
18501      29483.0        AW00029483     Jésus Navarro  Paris La Defense

          State-Province    Country-Region       Postal Code
0       [Not Applicable]  [Not Applicable]  [Not Applicable]
1             Queensland         Australia              4700
2               Victoria         Australia              3198
3               Tasmania         Australia              7001
4        New South Wales         Australia              2113
...                  ...               ...               ...
18497            Yveline            France             78000
18498            England    United Kingdom          SW19 3RU
18499             Bayern           Germany             95010
18500  Charente-Maritime            France             17490
18501     Hauts de Seine            France             92081

[18502 rows x 7 columns]

In [4]:
print(df_sales_order_data.head(2))
print(df_sales_territory_data.head(2))
print(df_sales_data.head(2))
print(df_reseller_data.head(2))
print(df_date_data.head(2))
print(df_product_data.head(2))
print(df_customer_data.head(2))

    Channel  SalesOrderLineKey Sales Order Sales Order Line
0  Reseller           43659001     SO43659      SO43659 - 1
1  Reseller           43659002     SO43659      SO43659 - 2
   SalesTerritoryKey     Region        Country          Group
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
   SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  \
0           43659001          676           -1         349      20170702
1           43659002          676           -1         350      20170702

   DueDateKey  ShipDateKey  SalesTerritoryKey  Order Quantity  Unit Price  \
0    20170712   20170709.0                  5               1    2024.994
1    20170712   20170709.0                  5               3    2024.994

   Extended Amount  Unit Price Discount Pct  Product Standard Cost  \
0         2024.994                        0              1898.0944
1         6074.982                        0              1898.0944

   Total Product Cost  Sales Amount
0           1898.0944      2024.994
1           5694.2832      6074.982
   ResellerKey       Reseller ID         Business Type          Reseller  \
0           -1  [Not Applicable]      [Not Applicable]  [Not Applicable]
1            1        AW00000001  Value Added Reseller      A Bike Store

               City    State-Province    Country-Region       Postal Code
0  [Not Applicable]  [Not Applicable]  [Not Applicable]  [Not Applicable]
1           Seattle        Washington     United States             98104
    DateKey       Date Fiscal Year Fiscal Quarter     Month     Full Date  \
0  20170701 2017-07-01      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 01
1  20170702 2017-07-02      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 02

   MonthKey
0    201707
1    201707
   ProductKey         SKU                    Product  Standard Cost  Color  \
0         210  FR-R92B-58  HL Road Frame - Black, 58       868.6342  Black
1         211  FR-R92R-58    HL Road Frame - Red, 58       868.6342    Red

   List Price          Model  Subcategory    Category
0      1431.5  HL Road Frame  Road Frames  Components
1      1431.5  HL Road Frame  Road Frames  Components
   CustomerKey       Customer ID          Customer              City  \
0         -1.0  [Not Applicable]  [Not Applicable]  [Not Applicable]
1      11000.0        AW00011000          Jon Yang       Rockhampton

     State-Province    Country-Region       Postal Code
0  [Not Applicable]  [Not Applicable]  [Not Applicable]
1        Queensland         Australia              4700

In [5]:
GMV = df_sales_data['Sales Amount'].sum()
print('gmv = : ' , GMV)

gmv = :  109809274.203

In [6]:
mprovit = GMV-df_sales_data['Total Product Cost'].sum() - df_sales_data['Unit Price Discount Pct'].sum()
Net_Provit_Margin = (mprovit/GMV*100)
print('Net_Provit_Margin :',Net_Provit_Margin ,' %')

Net_Provit_Margin : 11.430151359617202  %

In [7]:
print(df_date_data.head(2))

    DateKey       Date Fiscal Year Fiscal Quarter     Month     Full Date  \
0  20170701 2017-07-01      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 01
1  20170702 2017-07-02      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 02

   MonthKey
0    201707
1    201707